[package]
name = "message-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
merkle-tree = {path="../merkle-tree"}

k256 = "0.13.2"
rand_core = "0.6.4"